### ISSUE TITLE
gnofract4d, undefined symbol: 'arena_delete'

### ISSUE THREAD

**Issue by Pygmalion69** [fract4d/gnofract4d#242]
Ubuntu 20.04.3 LTS, Python 3.8.10:

```
(base) pygmalion@artemisia:~/git/gnofract4d$ /usr/bin/python ./setup.py build
running build
running build_py
running fract4d_build_py
running build_ext
running build_scripts
(base) pygmalion@artemisia:~/git/gnofract4d$ ./gnofract4d 
Traceback (most recent call last):
  File "/home/pygmalion/git/gnofract4d/fract4dgui/main_window.py", line 44, in do_activate
    self.mainWindow = MainWindow(self)
  File "/home/pygmalion/git/gnofract4d/fract4dgui/main_window.py", line 53, in __init__
    ApplicationWindow.__init__(self, application)
  File "/home/pygmalion/git/gnofract4d/fract4dgui/application_window.py", line 251, in __init__
    self.f = gtkfractal.T(application.compiler, self)
  File "/home/pygmalion/git/gnofract4d/fract4dgui/gtkfractal.py", line 455, in __init__
    Hidden.__init__(self, comp, width, height)
  File "/home/pygmalion/git/gnofract4d/fract4dgui/gtkfractal.py", line 68, in __init__
    self.try_init_fractal()
  File "/home/pygmalion/git/gnofract4d/fract4dgui/gtkfractal.py", line 82, in try_init_fractal
    self.f.compile()
  File "/home/pygmalion/git/gnofract4d/fract4d/fractal.py", line 629, in compile
    self.set_output_file(outputfile)
  File "/home/pygmalion/git/gnofract4d/fract4d/fractal.py", line 637, in set_output_file
    self.handle = fract4dc.pf_load(self.outputfile)
ValueError: /home/pygmalion/.gnofract4d-cache/fract4d_ba4354f31fa9a886bf0372b3303d3df3.so: undefined symbol: arena_delete
```

**Comment by DX-MON** [comment]
What version of gnofract4d are you using here? It's not mentioned

**Comment by Pygmalion69** [comment]
It's 4.3, but I cannot reproduce the issue.
